### ISSUE TITLE
Provide maven integration

### ISSUE THREAD

**Issue by piotr-j** [seannybgoode/libGDX-EvolveLiteMediaPlayerLibrary#4]
Currently it is fairly annoying to get this to work, proper maven or gradle stuff would make it a lot faster and less error prone. Dependencies should be pulled via maven as well.

**Comment by seannybgoode** [comment]
Believe it or not, the current dependency system is a little better than the original project. When I forked I had to troubleshoot just to get it to run, get the Xuggler libs, and then from there figure out that I needed slf4j. Those libs have been included in the project now. Will look at maven, possibly for 0.1.6, but it's not a top priority. All you should need is libGDX to get it to run (which is easy enough to handle manually).

**Comment by piotr-j** [comment]
In the repo, for xuggler there is a license, thats hardly enough. Slf4j doesnt contain jar/source either. Here is a pom.xml ive used to get this to work https://gist.github.com/piotr-j/ce88618e95baffb5204d

**Comment by seannybgoode** [comment]
Hm the jars should be there. Lemme see what's going on here.

**Comment by seannybgoode** [comment]
I'll include the pom.xml in the next push too.

**Comment by seannybgoode** [comment]
There, it's live. Let me know how that works out.

**Comment by seannybgoode** [comment]
Ohh it still didn't work. Apparently git doesn't like .jar files as much as I like self contained dependencies. Maven it is.

**Comment by seannybgoode** [comment]
closing
