### ISSUE TITLE
Lib doesnt compile as is.

### ISSUE THREAD

**Issue by piotr-j** [seannybgoode/libGDX-EvolveLiteMediaPlayerLibrary#5]
There are is a missing constant in VideoScreen, VIRTUAL_VP_HEIGHT. Node implementation is missing in Queue.

**Comment by seannybgoode** [comment]
Added Node into the included libs. Will look at VIRTUAL_VP_HEIGHT today.

**Comment by seannybgoode** [comment]
Fixed - 0.1.5
